tap "homebrew/bundle"
tap "homebrew/cask"

# brew formulaes
brew "coreutils"
brew "curl"
brew "go"
brew "detox"
brew "fzf"
brew "gh"
brew "git"
brew "git-crypt"
brew "graphviz"
brew "htop"
brew "hugo"
brew "jq"
brew "protobuf"
brew "warrensbox/tap/tfswitch"
brew "the_silver_searcher"
brew "tree"
brew "unrar"
brew "wget"
brew "youtube-dl"
brew "wifi-password"

# cask formulaes
cask "google-chrome"
cask "spotify"
cask "iterm2"
cask "slack"
cask "1password"
cask "postman"
cask "zoom"